[tool.poetry]
name = "pants-mono-lock"
version = "0.1.0"
description = ""
authors = ["Quentin Gaborit <quentin.gaborit@ledger.fr>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.2"
numpy = "^1.22.3"
click = "^8.1.3"
PyYAML = "^6.0"
setuptools = "^63.4.2"

[tool.poetry.dev-dependencies]
types-PyYAML = "^6.0.9"
pandas-stubs = "^1.4.2"
types-requests = "^2.28.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
