name: CI - AWS

on: [push, pull_request]

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'gbto' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Github Organisation
        run: "true"

  authenticate-to-aws:
    name: CI - AWS
    needs: org-check
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::895539818407:role/github-oidc
          aws-region: eu-west-1
      - name: Test AWS Creds
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
