name: CI - Pants

on: [push, pull_request]

permissions:
  packages: write
  contents: read

jobs:
  org-check:
    name: Check Github Organisation
    if: ${{ github.repository_owner == 'gbto' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Github Organisation
        run: "true"

  build-images:
    name: Lint > Build > Publish
    needs: org-check
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      # Checkout the repository on current branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^

      # Set-up Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Activate cache for pants files on the GitHub actions server
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: ${{ runner.os }}-

      # Perform pants bootstrap, linting, packaging and publishing
      - name: Bootstrap pants
        run: |
          ./pants --version

      - name: Check BUILD files
        run: ./pants tailor --check update-build-files --check

      - name: Lint changed code
        run: |
          ./pants --changed-since=origin/main --changed-dependees=transitive check lint

      - name: Package images
        run: |
          ./pants --changed-since=origin/main --changed-dependees=transitive check package

      - name: Push pants images
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          ./pants --changed-since=origin/main --changed-dependees=transitive check publish

      - name: Upload pants log
        uses: actions/upload-artifact@v2
        with:
          name: pants-log
          path: .pants.d/pants.log
        if: always() # Save log even on failures
